services:
  backend:
    build: ./Backend
    container_name: django_backend
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - Backend/.env
    depends_on:
      - redis

  redis:
    image: redis:8
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data: